# Generated by Django 2.2.28 on 2023-11-03 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0008_auto_20231005_0622'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0002_auto_20230913_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAccounting',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('unit_cd', models.CharField(help_text='3-character unit code', max_length=3, verbose_name='Unit Code')),
                ('division', models.CharField(help_text='4-character division code', max_length=4, verbose_name='Division')),
                ('organization', models.CharField(help_text='4-character organization code', max_length=4, verbose_name='Organization')),
                ('location', models.CharField(help_text='4-character location code', max_length=4, verbose_name='Location')),
                ('fund_type', models.CharField(help_text='3-character fund type code', max_length=3, verbose_name='Fund Type')),
                ('business_line', models.CharField(help_text='4-character business line code', max_length=4, verbose_name='Business Line')),
                ('account', models.CharField(help_text='5-character account code', max_length=5, verbose_name='Account')),
                ('gl_string', models.CharField(help_text='Generated GL string in the format: Unit [3]-Division [4]-Organization [4]-Location [4]-Fund Type [3]-Business Line [4]-Account [5]', max_length=27, verbose_name='GL String')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='department.Department', verbose_name='Department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('offering_unit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course.OfferingUnit', verbose_name='Offering Unit')),
            ],
            options={
                'verbose_name': 'historical accounting',
                'verbose_name_plural': 'historical accountings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('unit_cd', models.CharField(help_text='3-character unit code', max_length=3, verbose_name='Unit Code')),
                ('division', models.CharField(help_text='4-character division code', max_length=4, verbose_name='Division')),
                ('organization', models.CharField(help_text='4-character organization code', max_length=4, verbose_name='Organization')),
                ('location', models.CharField(help_text='4-character location code', max_length=4, verbose_name='Location')),
                ('fund_type', models.CharField(help_text='3-character fund type code', max_length=3, verbose_name='Fund Type')),
                ('business_line', models.CharField(help_text='4-character business line code', max_length=4, verbose_name='Business Line')),
                ('account', models.CharField(help_text='5-character account code', max_length=5, verbose_name='Account')),
                ('gl_string', models.CharField(help_text='Generated GL string in the format: Unit [3]-Division [4]-Organization [4]-Location [4]-Fund Type [3]-Business Line [4]-Account [5]', max_length=27, verbose_name='GL String')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.Department', verbose_name='Department')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('offering_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.OfferingUnit', verbose_name='Offering Unit')),
            ],
            options={
                'unique_together': {('department', 'offering_unit')},
            },
        ),
    ]
