# Generated by Django 2.2.28 on 2023-09-13 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sctnsubtitle',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offeringunit',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offeringexpttl',
            name='course_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offering_exp_course_section', to='course.CourseSection'),
        ),
        migrations.AddField(
            model_name='offeringexpttl',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_department', to='department.Department'),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='offering_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_offering_unit', to='course.OfferingUnit'),
        ),
        migrations.AddField(
            model_name='coursemtg',
            name='course_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_mtg_course_section', to='course.CourseSection'),
        ),
        migrations.AddField(
            model_name='coursemtg',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sctnsubtitle',
            unique_together={('year', 'term', 'offering_unit_cd', 'subj_cd', 'course_no', 'section_no')},
        ),
        migrations.AlterUniqueTogether(
            name='offeringunit',
            unique_together={('offering_unit_cd', 'offering_unit_campus', 'offering_unit_level')},
        ),
        migrations.AlterUniqueTogether(
            name='offeringexpttl',
            unique_together={('year', 'term', 'offering_unit_cd', 'subj_cd', 'course_no', 'supplment_cd')},
        ),
        migrations.AlterUniqueTogether(
            name='coursesection',
            unique_together={('year', 'term', 'reg_index_no', 'offering_unit_cd', 'subj_cd', 'course_no', 'course_suppl_cd', 'section_no')},
        ),
        migrations.AlterUniqueTogether(
            name='coursemtg',
            unique_together={('year', 'term', 'reg_index_no', 'mtg_day', 'start_time', 'end_time', 'bldg_cd', 'room_no')},
        ),
    ]
