# Generated by Django 2.2.28 on 2023-09-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_courseprereq_coursesectioncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='appointment_required',
            field=models.BooleanField(default=True),
        ),
    ]
