# Generated by Django 2.2.28 on 2023-09-29 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0006_coursesection_appointment_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('term', models.IntegerField(choices=[(0, 'Winter'), (1, 'Spring'), (7, 'Summer'), (9, 'Fall')])),
                ('tuition_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('offering_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.OfferingUnit')),
            ],
            options={
                'unique_together': {('offering_unit', 'year', 'term')},
            },
        ),
    ]
