# Generated by Django 3.2.23 on 2023-12-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20231226_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalofferingexpttl',
            name='expand_course_title_descr',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='offeringexpttl',
            name='expand_course_title_descr',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
