# Generated by Django 3.2.23 on 2023-12-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20231226_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalofferingexpttl',
            name='course_no',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='offeringexpttl',
            name='course_no',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
