# Generated by Django 3.2.23 on 2023-12-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20231226_0918'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sctnsubtitle',
            unique_together={('year', 'term', 'offering_unit_cd', 'subj_cd', 'course_no', 'section_no', 'supplment_cd')},
        ),
    ]
