# Generated by Django 2.2.28 on 2023-10-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20230925_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='employee_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Employee Number'),
        ),
    ]
