# Generated by Django 2.2.28 on 2023-10-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20231017_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name'),
        ),
    ]
