# Generated by Django 2.2.28 on 2023-10-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_auto_20231023_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='ssn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Social Security Number'),
        ),
    ]
