# Generated by Django 3.2.23 on 2024-01-04 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0008_historicalappointment_historicalinstructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='GAExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorCourseSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RecordNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='academic_year_title',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='background_collateral_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='background_collateral_type',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date_revised_sent_for_signature',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date_sent_for_signature',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date_signed_revised_appointment_letter_returned',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date_submitted_hcm',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='dept_comments',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='eci_processing_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='faculty_designation',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='instr_approved_course_salary',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='instr_comment',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='instr_course_salary',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='instr_role',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='instr_role_others',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='instruct_task',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='instruct_task_other',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='lecturer_fellow_pay_option',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='lecturer_fellow_salary',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='low_enroll',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='num_pays',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='ready_for_hcm',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='ready_for_hcm_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='record_no',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='sch_account_num',
        ),
        migrations.RemoveField(
            model_name='historicalappointment',
            name='academic_year_title',
        ),
        migrations.RemoveField(
            model_name='historicalappointment',
            name='background_collateral_date',
        ),
        migrations.RemoveField(
            model_name='historicalappointment',
            name='background_collateral_type',
        ),
        migrations.RemoveField(
            model_name='historicalappointment',
            name='date_revised_sent_for_signature',
        ),
        migrations.RemoveField(
            model_name='historicalappointment',
            name='date_sent_for_signature',
        ),
        migrations.RemoveField(
            model_name='historicalappointment',
            name='date_signed_revised_appointment_letter_returned',
        ),
        migrations.RemoveField(
            model_name='historicalappointment',
            name='date_submitted_hcm',
        ),
        migrations.RemoveField(
            model_name='historicalappointment',
            name='dept_comments',
        ),
        migrations.RemoveField(
            model_name='historicalappointment',
            name='eci_processing_date',
        ),
        migrations.RemoveField(
            model_name='historicalappointment',
            name='faculty_designation',
        ),
        migrations.RemoveField(
            model_name='historicalappointment',
            name='instr_approved_course_salary',
        ),
        migrations.RemoveField(
            model_name='historicalappointment',
            name='instr_comment',
        ),
        migrations.RemoveField(
            model_name='historicalappointment',
            name='instr_course_salary',
        ),
        migrations.RemoveField(
            model_name='historicalappointment',
            name='instr_role',
        ),
        migrations.RemoveField(
            model_name='historicalappointment',
            name='instr_role_others',
        ),
        migrations.RemoveField(
            model_name='historicalappointment',
            name='instruct_task',
        ),
        migrations.RemoveField(
            model_name='historicalappointment',
            name='instruct_task_other',
        ),
        migrations.RemoveField(
            model_name='historicalappointment',
            name='lecturer_fellow_pay_option',
        ),
        migrations.RemoveField(
            model_name='historicalappointment',
            name='lecturer_fellow_salary',
        ),
        migrations.RemoveField(
            model_name='historicalappointment',
            name='low_enroll',
        ),
        migrations.RemoveField(
            model_name='historicalappointment',
            name='num_pays',
        ),
        migrations.RemoveField(
            model_name='historicalappointment',
            name='ready_for_hcm',
        ),
        migrations.RemoveField(
            model_name='historicalappointment',
            name='ready_for_hcm_date',
        ),
        migrations.RemoveField(
            model_name='historicalappointment',
            name='record_no',
        ),
        migrations.RemoveField(
            model_name='historicalappointment',
            name='sch_account_num',
        ),
        migrations.AddField(
            model_name='appointment',
            name='accepted_low_be_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='alt_school_acct',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='approved_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='background_check_received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='background_check_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.backgroundcollateraltype'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='charging_instructions_processing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='overwrite_contact_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='overwrite_school_acct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='role_of_appointee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.appointeerole'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='special_contract_text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='accepted_low_be_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='alt_school_acct',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='approved_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='background_check_received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='background_check_status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appointment.backgroundcollateraltype'),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='charging_instructions_processing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='overwrite_contact_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='overwrite_school_acct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='role_of_appointee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appointment.appointeerole'),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='special_contract_text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalappointment',
            name='appointment_status',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalappointment',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ApprovedSalaryHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_salary', models.DecimalField(decimal_places=2, max_digits=22)),
                ('approval_date', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='appointment.appointment')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentPastSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(choices=[('0', 'Winter'), ('1', 'Spring'), ('7', 'Summer'), ('9', 'Fall'), ('2', 'First Time')], max_length=6, verbose_name='Term')),
                ('year', models.CharField(max_length=4, verbose_name='Year')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='Salary')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_salaries', to='appointment.appointment')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminAppointmentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_comments', to='appointment.appointment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='ga_ta_experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.gaexperience'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='instructor_course_salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.instructorcoursesalary'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='record_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.recordnumber'),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='ga_ta_experience',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appointment.gaexperience'),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='instructor_course_salary',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appointment.instructorcoursesalary'),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='record_number',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appointment.recordnumber'),
        ),
    ]
