# Generated by Django 3.2.23 on 2024-01-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_auto_20240110_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinstructor',
            name='ssn',
            field=models.TextField(blank=True, null=True, verbose_name='Social Security Number'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='ssn',
            field=models.TextField(blank=True, null=True, verbose_name='Social Security Number'),
        ),
    ]
