# Generated by Django 3.2.23 on 2024-01-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_auto_20240111_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentpastsalary',
            name='term',
            field=models.IntegerField(choices=[('0', 'Winter'), ('1', 'Spring'), ('7', 'Summer'), ('9', 'Fall'), ('2', 'First Time')], verbose_name='Term'),
        ),
    ]
