# Generated by Django 3.2.23 on 2024-01-12 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0012_alter_appointmentpastsalary_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinstructor',
            name='visa_type',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='visa_type',
        ),
        migrations.CreateModel(
            name='VisaPermitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='historicalinstructor',
            name='visa_permit_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appointment.visapermittype', verbose_name='Visa/Permit Type'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='visa_permit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.visapermittype', verbose_name='Visa/Permit Type'),
        ),
    ]
