# Generated by Django 3.2.23 on 2024-01-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_auto_20240112_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentpastsalary',
            name='term',
            field=models.IntegerField(choices=[(0, 'Winter'), (1, 'Spring'), (7, 'Summer'), (9, 'Fall'), (2, 'First Time')], verbose_name='Term'),
        ),
    ]
