# Generated by Django 3.2.23 on 2023-12-21 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('template_type', models.CharField(choices=[('UNION_CONTRACT', 'Union Contract'), ('NON_UNION_CONTRACT', 'Non Union Contract'), ('ON_LOAD_CONTRACT', 'On Load Contract')], max_length=100)),
                ('content', models.TextField()),
                ('default_content', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
