# Generated by Django 3.2.24 on 2024-02-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_historicalcontact_historicaldepartment_historicaldepartmentuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldepartment',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
